# Layer configuration for meta-oasis

# Add 'meta-oasis' to the collection of layers
BBFILE_COLLECTIONS += "meta-oasis"

# Specify the pattern for finding recipes in the 'meta-oasis' layer
BBFILE_PATTERN_meta-oasis = "^${LAYERDIR}/"

# Allow recipes in recipes-* directories to be parsed
BBFILES:append = " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

# Choose the layer priority. Higher number = higher priority. "13" is chosen to
# override ROS layers, which have priorities in the 10-12 range.
BBFILE_PRIORITY_meta-oasis = "13"

# Lists the other layers that 'meta-oasis' depends on
LAYERDEPENDS_meta-oasis = " \
    core \
    meta-kodi \
    openembedded-layer \
    ros-common-layer \
"

# Yocto compatibility
LAYERSERIES_COMPAT_meta-oasis = "scarthgap"
